apiVersion: v1
kind: Service
metadata:
  name: todo-backend
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "todo-app.labels" . | nindent 4 }}
    component: backend
spec:
  type: NodePort
  selector:
    {{- include "todo-app.backend.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.backend.port }}
      targetPort: {{ .Values.backend.port }}
      nodePort: {{ .Values.backend.nodePort }}
      protocol: TCP
      name: http
