apiVersion: v1
kind: ConfigMap
metadata:
  name: todo-app-config
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "todo-app.labels" . | nindent 4 }}
data:
  CORS_ORIGINS: {{ .Values.backend.env.CORS_ORIGINS | quote }}
  ENVIRONMENT: {{ .Values.backend.env.ENVIRONMENT | quote }}
