apiVersion: v1
kind: Service
metadata:
  name: todo-frontend
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "todo-app.labels" . | nindent 4 }}
    component: frontend
spec:
  type: NodePort
  selector:
    {{- include "todo-app.frontend.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.frontend.port }}
      targetPort: {{ .Values.frontend.port }}
      nodePort: {{ .Values.frontend.nodePort }}
      protocol: TCP
      name: http
